#!/bin/bash

source packer-build.conf

show_usage() {
cat << EOF

usage: build-image [IMAGE TYPE]

  IMAGE_TYPE
      light - build packer light image with docker cli
              Default build is light when build type not specified
      full  - build package full image with docker cli 

EOF
}

build_image() {
	local IMAGE_TYPE=$1
	case $IMAGE_TYPE in
		light)
			SOURCE_IMAGE="hashicorp/packer:$IMAGE_TYPE-$PACKER_LIGHT_UPSTREAM_VERSION"
			TARGET_IMAGE="aldrinebaroi/packer:$IMAGE_TYPE-$PACKER_LIGHT_UPSTREAM_VERSION"
			TARGET_IMAGE_LATEST="aldrinebaroi/packer:$IMAGE_TYPE"
			;;
		full)
			SOURCE_IMAGE="hashicorp/packer:$IMAGE_TYPE-$PACKER_FULL_UPSTREAM_VERSION"
			TARGET_IMAGE="aldrinebaroi/packer:$IMAGE_TYPE-$PACKER_FULL_UPSTREAM_VERSION"
			TARGET_IMAGE_LATEST="aldrinebaroi/packer:$IMAGE_TYPE"
			;;
	esac
	docker build \
		-t $TARGET_IMAGE \
		-t $TARGET_IMAGE_LATEST \
		--build-arg SOURCE_IMAGE="$SOURCE_IMAGE" \
		.
	(( $? )) && echo "Failed to build image." && exit 1
	echo "Successfully build $TARGET_IMAGE image."
}

IMAGE_TYPE=${1// /}
IMAGE_TYPE=${IMAGE_TYPE,,}
[[ -z ${IMAGE_TYPE} ]] && IMAGE_TYPE="light"

case $IMAGE_TYPE in 
	light|full)
		build_image $IMAGE_TYPE
		;;
	help)
		show_usage
		;;
	*)
		echo "Invalid build type [$IMAGE_TYPE]"
		;;
esac 

#::END::
