#!/bin/bash

packer_execute() {
	echo ""
	source packer.conf 
	local CMD=$1
	local INTERACTIVE=""
	case $CMD in
		console)
			INTERACTIVE="-it"
			;;
	esac
	echo ""
	# Set workspace
	[[ -z ${WORKSPACE_DIR// /} ]] && WORKSPACE_DIR=$(pwd)/workspace
	[[ ! $WORKSPACE_DIR =~ ^\/ ]] && WORKSPACE_DIR=$(pwd)/$WORKSPACE_DIR
	# Map Docker sock volume if needed
	MAP_DOCKER_SOCK_VOLUME="-v /var/run/docker.sock:/var/run/docker.sock"
	[[ ! ${USE_DOCKER^^} == "Y" ]] && MAP_DOCKER_SOCK_VOLUME=""
	# Set packer image
	[[ -z ${PACKER_IMAGE_TYPE// /} ]] && PACKER_IMAGE_TYPE="light"
	[[ -z ${PACKER_IMAGE// /} ]] && PACKER_IMAGE="aldrinebaroi/packer:$PACKER_IMAGE_TYPE"
	# Check if workspace directory exist
	[[ -f $WORKSPACE_DIR ]] && echo "Workspace directory doesn't exist. aborting..." && exit 1
	docker run \
		${INTERACTIVE} \
		--rm \
		-v $WORKSPACE_DIR:/workspace \
		${MAP_DOCKER_SOCK_VOLUME} \
		-w /workspace \
		-e PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins \
		$PACKER_IMAGE $@
	echo "" 
}

help() {
	cat <<-HELPTEXT

	Usage: packer [--version] [--help] <command> [<args>]

	Available commands are:

	build           build image(s) from template
	console         creates a console for testing variable interpolation
	fix             fixes templates from old versions of packer
	fmt             Rewrites HCL2 config files to canonical format
	hcl2_upgrade    transform a JSON template into an HCL2 configuration
	init            Install missing plugins or upgrade plugins
	inspect         see components of a template
	validate        check that a template is valid
	version         Prints the Packer version

	HELPTEXT
}

CMD=$1
shift 1
ARGS="$@"

case $CMD in
	--version)	;& 
	--help)		;&
	build)		;&
	console)	;&
	fix)		;&
	fmt)		;&
	hcl2_upgrade)	;&
	init)		;&
	inspect)	;&
	validate)	;&
	version)
		packer_execute $CMD $ARGS
		;;
	*)
		[[ -z ${CMD// /} ]] && help && exit 0
		echo "Invalid request: [$CMD]"
		exit 1
		;;
esac

#::END::
